#!/usr/bin/env sh

connection_host=$(cat ~/.ssh/config ~/.ssh/configs/* | grep '^Host' | cut -d ' ' -f 2 | dmenu)
#connection_user=$(cat /etc/passwd | cut -d ':' -f 1 | dmenu)

if [[ $connection_host ]]; then
	notify-send "Connecting to $connection_host."
	st ssh $connection_host
fi
