#!/usr/bin/env sh

default_source=$(pulsemixer --list-sources | grep Default | awk '{print substr($3, 1, length($3)-1)}')
pulsemixer --toggle-mute --id $default_source

state=$(pulsemixer --get-mute --id $default_source)

if [[ $state == 1 ]]; then
	notify-send " MUTE MIC"
	mv ~/.config/perso/tools/actions/scripts/sound/MUTE_MIC ~/.config/perso/tools/actions/scripts/sound/UNMUTE_MIC
else
	notify-send " UNMUTE MIC"
	mv ~/.config/perso/tools/actions/scripts/sound/UNMUTE_MIC ~/.config/perso/tools/actions/scripts/sound/MUTE_MIC
fi
