#!/usr/bin/env sh

pulsemixer --toggle-mute

state="$(pulsemixer --get-mute)"

if [[ $state == 1 ]]; then
	mv ~/.config/perso/tools/actions/scripts/sound/MUTE ~/.config/perso/tools/actions/scripts/sound/UNMUTE
	notify-send " MUTE"
else
	mv ~/.config/perso/tools/actions/scripts/sound/UNMUTE ~/.config/perso/tools/actions/scripts/sound/MUTE
	notify-send " UNMUTE"
fi
