#!/bin/bash

occupied_desktop=$(bspc query -T -d | jq -r .root)

if [[ "$occupied_desktop" == "null" ]]; then
  class_to_use="wikif" ;
else
  class_to_use="wiki" ;
fi

/home/alex/apps/suckless/focus-st/st -c "$class_to_use" -f "Cousine for Powerline:style=Regular:size=18" -e ~/.config/perso/focus/focusvim "-S ~/.vim/sessions/focus.vim"

